### PR TITLE
Registered all created blocks as blocks and items.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
And modified API design

**Comment by Xesau** [comment]
I'd like to see 2DRegion back
(2D regions are commonly used in minigames, especially the isInside...)

**Comment by Xesau** [comment]
Oh well, I'll do that manually

**Comment by ghost** [comment]
Well I don't really see a purpose for it, because if you have a region 1 block high, you can just use a 3D region for it...

**Comment by Xesau** [comment]
Its not one block high? It's a 2D region from upper view.
I merged it with master. There were some conflicts somehow.

I also changed back the Block to a class. Block is not an interface but a class because it is an object.

**Comment by ghost** [comment]
Oh okay. But with the block, I was thinking have an interface in the API and then have the implementation of it in the actual server

**Comment by ghost** [comment]
Like if somebody is using the API, they don't need to have an object, and interface is just fine for that. And they shouldn't use the constructor, just get the block from world or whatever

**Comment by Xesau** [comment]
@nverdierDev Please explain me what's the point in having an object implementing a Block interface? There won't be multiple types of blocks, it's just a block, a representation of a set of bits in the memory. Interface, why??

**Comment by Xesau** [comment]
Oh, and "having an implementation in the actual server"
This API isn't just for the server. It's for the whole game. I understand your confusion though.

**Comment by nverdierDev** [comment]
Oh I see, thanks for clarifying. So there isn't going to be any implementation of the API, it is the implementation?

**Comment by Xesau** [comment]
An API is a way to communicate between two computers, a language, one could say. For sure it must be implemented, because what's the need of a language when the person you talk to doesn't understand it? That does not immediately mean every single thing must be an interface.

**Comment by ghost** [comment]
Yeah I understand ;3

**Comment by ghost** [comment]
Also the branch created by this PR is still active...

**Comment by Xesau** [comment]
Ill delete it

**Pull request closed without merging**
