### PR TITLE
Deleted client module as libGDX isn't going to be used

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by beeselmane** [comment]
Did you just remove the folder?

**Comment by ghost** [comment]
As opposed to what?

**Comment by beeselmane** [comment]
Nothing, I just thought it was funny xD

**Comment by ghost** [comment]
So confused.

**Comment by beeselmane** [comment]
Nevermind... carry on xP

**Comment by ghost** [comment]
Shall do. Have fun.

**Pull request merged**
