### PR TITLE
Details in comment. And the update to pom.xml is just reverting updates I made on local.

### PR DESCRIPTION
**Pull request by ghost**
Removed some useless stuff (e.g. explicit type arguments, public modifier in interface methods, unnecessary String assignments)

Changed some stuff to have method references instead of lambdas.

### CODE REVIEW

**Comment by Xesau** [comment]
Ehm, the API is to be rewritten soon.
It's not encouraged to work on it anymore, as it will not be used

**Comment by Xesau** [comment]
Rather help designing the new API here:
https://github.com/Cubition/Cubition/blob/master/New%20API%20design.jsd :)

**Comment by ghost** [comment]
Oh haha ok. So that file in the main directory has the new, current layout for the API? Has that been started on yet or does it need to be?

**Comment by ghost** [comment]
Got it

**Comment by Xesau** [comment]
Is has ven and needs extension.
I got some notes on my phone, will merge them now

**Comment by ghost** [comment]
Ok, so do you want the file you linked to above need to be worked on before any code is done? And what is going to stay with the current API? Sorry for the load of questions, just don't want to do it other than how it is wanted haha

**Comment by Xesau** [comment]
Yes, on that file should be worked. The design of the API should first be done, so we have a better oversight of how things will work. When we have something, I'll run it through my self-made preprocessor and then we can start making the real code. Never tried this before: we'll see if it works and if so, we will probably save a lot of time.

**Pull request closed without merging**
